CREATE TABLE qa (
  id BIGSERIAL PRIMARY KEY
  , tool_id bigint NOT NULL
  , question TEXT
  , answer TEXT
  , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP WITH TIME ZONE
);
